### ISSUE TITLE
Add Attachments, CC and BCC

### ISSUE THREAD

**Issue by bitwisebro** [cinotify/github-action#11]
I'd love to know how can I send the Attachments and add CC and BCC to the email

**Comment by derrick-ejan-rs** [comment]
> I'd love to know how can I send the Attachments and add CC and BCC to the email

I too would like to know if this is possible. Our use case is adding artifact file as an attachment to the email.

**Comment by jshawl** [comment]
I think this can be built! I just need to:
1. try out sharing artifacts between jobs
2. implement attachments in the API
3. implement attachments in the JS client
4. implement attachments in this GitHub action.

I'll check it out and report back!

**Comment by jshawl** [comment]
@bitwisebro @derrick-ejan-rs I've added a new option `attachment`: https://github.com/marketplace/actions/cinotify-email#example-usage

Try it out and let me know what you think! 

Also for CC  you can comma-separate the `to`, like: `to: jesse1@jesse.sh,jesse2@jesse.sh`
☝️ I did it this way for backwards compatibility with older integrators, but feel free to open a new issue for a feature request. 

Thanks!

**Comment by derrick-ejan-rs** [comment]
> I think this can be built! I just need to:
> 
> 1. try out sharing artifacts between jobs
> 2. implement attachments in the API
> 3. implement attachments in the JS client
> 4. implement attachments in this GitHub action.
> 
> I'll check it out and report back!

@jshawl  just reporting back its working as intended. appreciate the quick turnaround with adding this.

**Comment by jshawl** [comment]
Glad to hear it! I'll close out this issue but let me know if there's anything else I can help with - thank you!
