### ISSUE TITLE
Node 20

### ISSUE THREAD

**Issue by Dafnik** [cinotify/github-action#16]
Node16 has been deprecated an it's not recommended for usage any more.

Announcement: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by jshawl** [comment]
I think this is the culprit! https://github.com/cinotify/github-action/blob/54636e4cba2c7409a15a7061dcfb9af9eae18672/action.yml#L20 will see if I can publish a fix soon
