### ISSUE TITLE
The content type must be a string 

### ISSUE THREAD

**Issue by chandrasekhar7** [cinotify/github-action#21]
When I keep the sonarqube url  link in the action it's throwing as below. can you please look into this earlier it was working.

{"error":"The content type must be a string at least one character in length.":

example:

      - name: Send success notification
        if: always()
        uses: cinotify/github-action@main
        with:
          to: 'XXXXXXXXX@gmail.com'
          subject: 'testone'
          body: |
            'Test  '
            Job Details:
            Job Name: ${{ github.job }}
            Workflow: ${{ github.workflow }}
            Commit: ${{ github.sha }}
            Repository: ${{ github.repository }}
            type: 'text/html'
            SonarQube_URL: 'https://xxxxxxx/dashboard?branch=staging&id=xxxx_xxx_AYx87CNo85rvmfbTxLEv'

**Comment by jshawl** [comment]
sure - it looks like `type` is nested under `body` - is that intentional? I also have set this up to fallback to `text/plain` if a content type is not provided - https://github.com/cinotify/api/blob/ac25e35fa9501ba81c8b2a6e2ee74124d4351c1e/src/mail.js#L6

**Comment by derrick-ejan-rs** [comment]
@jshawl  I am also receiving the same error and has been fine until a few days ago.  Thanks!
![image](https://github.com/cinotify/github-action/assets/109308975/1a278c4b-7db1-443c-80e9-d47e4e1e35d0)

**Comment by jshawl** [comment]
sorry about that @derrick-ejan-rs @chandrasekhar7 - I have pushed a fix for this, do you mind retrying the build? thank you!

**Comment by derrick-ejan-rs** [comment]
> sorry about that @derrick-ejan-rs @chandrasekhar7 - I have pushed a fix for this, do you mind retrying the build? thank you!

@jshawl  we had a new build run and it was successful this time but no email was received.   I will report back if it occurs again on another build of ours.

**Comment by derrick-ejan-rs** [comment]
> > sorry about that @derrick-ejan-rs @chandrasekhar7 - I have pushed a fix for this, do you mind retrying the build? thank you!
> 
> @jshawl we had a new build run and it was successful this time but no email was received. I will report back if it occurs again on another build of ours.

We ran a new build again and step did not fail but no email was received.  We are sending the email to two different email addresses and neither had the notification.

**Comment by jshawl** [comment]
@derrick-ejan-rs are you able to provide more information about your setup? you are welcome to email me at jesse@jesse.sh if it is private or if you don't want to include those details on this public github thread. thank you!

**Comment by derrick-ejan-rs** [comment]
@jshawl looks like its working now. Thanks for the quick fix.

**Comment by jshawl** [comment]
That is great news! Thanks for reaching out and feel free to open a new issue if you have any questions or suggestions!

**Comment by chandrasekhar7** [comment]
@jshawl Working now. Thank You so much
