### ISSUE TITLE
Attachment is not happening

### ISSUE THREAD

**Issue by chandraarlagadda** [cinotify/github-action#22]
while attaching the file under attachment parameter. this functionality is not working. can you please guide me if I am doing something wrong here.

            Job Name: ${{ github.job }}
            Workflow: ${{ github.workflow }}
            Commit: ${{ github.sha }}
            Repository: ${{ github.repository }}
            ZAP Scan Report: ${{ env.ARTIFACTS_URL }}
            attachment: "${{ github.workspace }}/report.html"

**Comment by jshawl** [comment]
I've not used `${{github.workspace}}` before. Is that needed? e.g. can the `attachment` line be `attachment: "report.html"`?

**Comment by chandraarlagadda** [comment]
${{ github.workspace }} this is directory path  where report.html file is stored.

even I used as report.html file. the file is not attached in the mail. Can you please help on the @jshawl

**Comment by jshawl** [comment]
interesting... I just tried this https://github.com/cinotify/github-actions-example/pull/6/files and I received the attachment correctly! I'm unable to see the individual contents of CINotify emails though it looks like the emails are being delivered successfully. How else can I help troubleshoot?

**Comment by chandraarlagadda** [comment]
sorry @jshawl it was my mistake I have kept attachment parm in side the body parameter. after the correction it is working as expected. thank you for prompt supporting

**Comment by chandraarlagadda** [comment]
it's working for me
