### ISSUE TITLE
Multiple recipients.

### ISSUE THREAD

**Issue by victor-shelepen** [cinotify/github-action#4]
It seems. It does not send emails to different recipients at once.

**Comment by jshawl** [comment]
@victor-shelepen i could probably implement this functionality for you. Do you mind sharing what code you tried to send to multiple recipients? I will think about it some too thank you

**Comment by jshawl** [comment]
I went ahead and added support for comma-separated emails, because a lot of folks were trying that first:

```yaml 
to: first@example.com,second@example.com,third@example.com
```

but if you have any other ideas or feedback feel free to reopen or comment back. Thanks!
