### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by gitroli** [cinotify/github-action#6]
Your certificate for mails is expired, can you fix?

**Comment by mahendrapazcare** [comment]
certificate has expired giving this error every time .. please update the certificate.

**Comment by jshawl** [comment]
ack - looking into this:

https://github.com/cinotify/app/blob/a2e05b5f687d14eb01479a6ed19319721221d020/app/models/notification.rb#L14-L15
but no issues with sendgrid - https://status.sendgrid.com/

**Comment by jshawl** [comment]
@gitroli  @mahendrapazcare can you confirm this is resolved?

**Comment by gitroli** [comment]
It works now, thx
